### ISSUE TITLE
Cool project

### ISSUE THREAD

**Issue by hyenasky** [Talon396/WolfBox#1]
hey! i think this project is cool. @ry755 and i wanna chat with you, do you have discord or anything like that? sorry to ask in a gh issue, but you don't list contact info anywhere i could find.

**Comment by TalonFloof** [comment]
@hyenasky @ry755 I'd be happy to talk to you guys! My Discord username is TalonFox#3593

**Comment by ry755** [comment]
Oh it looks like you have friend requests disabled. My username is ryfox#7632

**Comment by TalonFloof** [comment]
Oops, I enabled it now
